完成基本功能模块
FeixiDev/LogToExcel pull request #1
Opened 2022-12-07 15:36 UTC by shikifyj

JSON文件读取
数据处理
转换为Excel

2022-12-12 10:15 UTC, mattie-feng requested changes

2022-12-12 10:15 UTC, mattie-feng commented on action.py
> +                code_list[i] = 'Partial Content'
使用字典写会更好吧

2022-12-12 10:15 UTC, mattie-feng commented on action.py
> +        ip_data_list = []
写在 with 外

2022-12-12 10:15 UTC, mattie-feng commented on action.py
> +            time_list[i] = time_list[i][:19]
可以处理字符串而不是列表

2022-12-12 10:15 UTC, mattie-feng commented on contrl.py
> +        sheet_name = re.findall('2.*?(?=.json)',(file_name_list[i]))
"2." 是为了匹配什么

2022-12-12 10:15 UTC, mattie-feng commented on action.py
> +    excel_name = excel_path + f'/vxTEL_audit_{excel_time}.xlsx'
用 发-string 就不用 +  了

2022-12-12 10:15 UTC, mattie-feng commented on action.py
> +            time_list[i] = time_list[i][:19]
可以处理字符串而不是列表

2022-12-12 10:15 UTC, mattie-feng commented on contrl.py
> +        sheet_name = re.findall('2.*?(?=.json)',(file_name_list[i]))
"2." 是为了匹配什么

2022-12-12 10:15 UTC, mattie-feng commented on action.py
> +    excel_name = excel_path + f'/vxTEL_audit_{excel_time}.xlsx'
用 发-string 就不用 +  了

2022-12-12 10:15 UTC, mattie-feng commented on main.py
> +        if args.argA:
argA 命名 => path
argB 同上，改掉

2022-12-15 09:18 UTC, shikifyj commented on action.py
> +            time_list[i] = time_list[i][:19]
这里处理的就是每个时间的字符串

2022-12-15 09:19 UTC, shikifyj commented on contrl.py
> +        sheet_name = re.findall('2.*?(?=.json)',(file_name_list[i]))
ks-logstash-auditing-2022.11.28.json -------'2.*?(?=.json)' --------11.28

2022-12-15 09:20 UTC, shikifyj commented on contrl.py
> +        sheet_name = re.findall('2.*?(?=.json)',(file_name_list[i]))
如果时间变成了2023 得改成3，目前没想到更好得解决办法

2022-12-20 05:59 UTC, merged